pipeline {
  agent any

  options {
    buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '5', daysToKeepStr: '', numToKeepStr: '5')
  }
  
  stages {

    stage('Hello') {
      steps {
        sh '''
          java -version
        '''
      }
    }

    stage('cat README') {
      //when {
      //  branch "test*"
      //}

      steps {
        configFileProvider(
        [configFile(fileId: 'service_dockerfile', variable: 'DOCKERFILE_CONTENT')]){
          sh '''
          ls -a
          echo "ABC"
          cat README.md
          cat ${DOCKERFILE_CONTENT}
          '''
        }

        /*configFileProvider(
        [configFile(fileId: 'service_dockerfile', variable: 'DOCKERFILE_CONTENT')]){
          sh '''
          ls -a
          echo "ABC"
          cat README.md
          echo ${DOCKERFILE_CONTENT}
          '''
        }*/
      }
    }
  }
}